import { MESSAGE_TYPE } from "../constants/interview";
import { STATUS_LABEL, formatDateTime } from "./sessionSummary";
import { parseRetrospective } from "./retrospective";
import { COMPANY_TYPES, EXPERIENCE_LEVELS } from "../constants/interview";

/**
 * 세션 1건 + 메시지 배열 → Markdown 문서 한 덩어리.
 *
 * 출력 구조:
 *   # 🎭 {직무} 면접 회고
 *   > 시작 ... · 종료 ... · 상태
 *
 *   ## 📋 면접 환경
 *   | 항목 | 값 |
 *   ...
 *
 *   ## 🏁 회고 (있을 때만)
 *   ### 전체 평가 / 강점 / 개선점 / Verdict / 평균 점수
 *
 *   ## 💬 전체 대화
 *   ### Q1. ...
 *   **A.** ...
 *   **Feedback** ...
 *   ### Follow-up. ...
 *
 * @param {Object} session
 * @param {Array}  messages
 * @returns {string}
 */
export function buildSessionMarkdown(session, messages) {
  const lines = [];

  const companyLabel =
    COMPANY_TYPES.find((c) => c.id === session.companyType)?.label ??
    session.companyType;
  const expLabel =
    EXPERIENCE_LEVELS.find((e) => e.id === session.experienceLevel)?.label ??
    "—";
  const techList =
    session.techStack?.length > 0 ? session.techStack.join(", ") : "(미지정)";

  // ─── 헤더 ────────────────────────────────────────────────
  lines.push(`# 🎭 ${session.jobRole} 면접 회고`);
  lines.push("");

  const meta = [];
  meta.push(`시작 ${formatDateTime(session.startedAt)}`);
  if (session.endedAt) meta.push(`종료 ${formatDateTime(session.endedAt)}`);
  meta.push(`상태 ${STATUS_LABEL[session.status] ?? session.status}`);
  lines.push(`> ${meta.join(" · ")}`);
  lines.push("");

  // ─── 면접 환경 ───────────────────────────────────────────
  lines.push("## 📋 면접 환경");
  lines.push("");
  lines.push("| 항목 | 값 |");
  lines.push("|------|-----|");
  lines.push(`| 직무 | ${escapeCell(session.jobRole)} |`);
  lines.push(`| 회사 타입 | ${escapeCell(companyLabel)} |`);
  lines.push(`| 경력 수준 | ${escapeCell(expLabel)} |`);
  lines.push(`| 기술 스택 | ${escapeCell(techList)} |`);
  lines.push("");

  // ─── 회고 ────────────────────────────────────────────────
  const retro = parseRetrospective(session.retrospective);
  if (retro) {
    lines.push("## 🏁 회고");
    lines.push("");

    if (retro.overall) {
      lines.push("### 전체 평가");
      lines.push("");
      lines.push(retro.overall.trim());
      lines.push("");
    }

    if (Array.isArray(retro.strengths) && retro.strengths.length > 0) {
      lines.push("### 👍 강점");
      lines.push("");
      for (const s of retro.strengths) lines.push(`- ${s}`);
      lines.push("");
    }

    if (Array.isArray(retro.improvements) && retro.improvements.length > 0) {
      lines.push("### 💡 개선점");
      lines.push("");
      for (const s of retro.improvements) lines.push(`- ${s}`);
      lines.push("");
    }

    if (retro.verdict) {
      lines.push("### 최종 평가");
      lines.push("");
      lines.push(`> ${retro.verdict}`);
      lines.push("");
    }

    if (typeof retro.finalScore === "number") {
      lines.push(`**답변 평균 점수**: ${retro.finalScore} / 10`);
      lines.push("");
    }
  }

  // ─── 대화 본문 ───────────────────────────────────────────
  lines.push("## 💬 전체 대화");
  lines.push("");

  let mainQIdx = 0;
  let followIdxWithinQ = 0;

  for (const msg of messages) {
    switch (msg.type) {
      case MESSAGE_TYPE.OPENING:
        lines.push("### 🎬 Opening");
        lines.push("");
        lines.push(msg.content.trim());
        lines.push("");
        break;

      case MESSAGE_TYPE.QUESTION:
        mainQIdx += 1;
        followIdxWithinQ = 0;
        lines.push(`### Q${mainQIdx}. ${msg.content.trim()}`);
        lines.push("");
        break;

      case MESSAGE_TYPE.ANSWER:
        lines.push("**A.**");
        lines.push("");
        lines.push(indentBlock(msg.content.trim(), "> "));
        lines.push("");
        break;

      case MESSAGE_TYPE.FEEDBACK: {
        const fb = safeJson(msg.content) || {};
        lines.push("**🧭 Feedback**");
        lines.push("");
        if (typeof fb.score === "number") {
          lines.push(`- **Score**: ${fb.score} / 10`);
        }
        if (fb.strengths) {
          lines.push(`- 👍 ${oneLine(fb.strengths)}`);
        }
        if (fb.weaknesses) {
          lines.push(`- 🤔 ${oneLine(fb.weaknesses)}`);
        }
        lines.push("");
        break;
      }

      case MESSAGE_TYPE.FOLLOW_UP:
        followIdxWithinQ += 1;
        lines.push(
          `### ↳ Q${mainQIdx}-${followIdxWithinQ} (Follow-up). ${msg.content.trim()}`,
        );
        lines.push("");
        break;

      case MESSAGE_TYPE.CLOSING:
        lines.push("### 🏁 Closing");
        lines.push("");
        lines.push(`> ${msg.content.trim()}`);
        lines.push("");
        break;

      default:
        // 알 수 없는 타입은 건너뜀
        break;
    }
  }

  // ─── 푸터 ────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "🎭 *Generated by [Interview Simulator](https://github.com/Dev-2A/interview-simulator) — Claude를 면접관으로 두는 AI 면접 연습 도구*",
  );

  return lines.join("\n");
}

/**
 * 표 셀에 안전하게 들어가도록 파이프와 줄바꿈을 이스케이프.
 */
function escapeCell(text) {
  if (!text) return "";
  return String(text).replace(/\|/g, "\\|").replace(/\n+/g, " ");
}

/**
 * 여러 줄 텍스트에 동일한 prefix를 붙인다. 답변 인용 블록용.
 */
function indentBlock(text, prefix) {
  return text
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n");
}

/**
 * 피드백 strengths/weaknesses는 한 줄 요약으로 노출.
 * 너무 길면 자동 줄바꿈이 잘 안 되므로 줄바꿈을 공백으로 치환.
 */
function oneLine(text) {
  return String(text ?? "")
    .replace(/\s+/g, " ")
    .trim();
}

function safeJson(s) {
  try {
    return JSON.parse(s);
  } catch {
    return null;
  }
}

/**
 * 파일명 안전화: 한글/영문/숫자/대시/언더스코어만 남기고 나머지는 -로 치환.
 */
export function buildExportFilename(session) {
  const date = new Date(session.startedAt);
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");

  const safeRole = (session.jobRole || "session")
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 40);

  return `${y}-${m}-${d}-${safeRole}-면접.md`;
}

/**
 * 브라우저에서 텍스트를 .md 파일로 다운로드한다.
 */
export function downloadMarkdown(filename, markdown) {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // 다음 마이크로태스크에서 해제 (Safari 호환)
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/**
 * 클립보드에 텍스트를 복사. navigator.clipboard 미지원 시 textarea 폴백.
 *
 * @returns {Promise<boolean>}
 */
export async function copyToClipboard(text) {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // 폴백으로 진행
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
